server:
  port: 66
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 #不限制请求体大小
spring:
  application:
    name: main-service
  profiles:
    active: dev #dev-本地开发环境;prod-生产环境;test-测试环境;
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848  # 确保这里有一个空格
        username: nacos              # 用户名
        password: nacos              # 密码
#日志级别
logging:
  level:
    root: info