server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # 不限制请求体大小
spring:
  application:
    name: file-service
  profiles:
    active: dev #dev-本地开发环境;prod-生产环境;test-测试环境;
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#日志级别
logging:
  level:
    root: info

minio:
  endpoint: http://127.0.0.1:9000
  fileHost: http://127.0.0.1:9000
  bucketName: wechat
  accessKey: imooc
  secretKey: imooc123456