server:
  port: 88
spring:
  data:
      redis:
        host: 127.0.0.1
        port: 5379
        database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 确保这里有一个空格
        username: nacos              # 用户名
        password: nacos              # 密码
